### ISSUE TITLE
" does not contain a definition for"

### ISSUE THREAD

**Issue by kfill420** [Herysia/AmongUsTryhard#2]
Hello,
 download your sources to adapte it to my modded game but i have lots of error "does not contain a definition for.."
 however I have installed the dependencies well, so I do not understand.
 https://imagizer.imageshack.com/img923/4725/yWCM9T.png
 Can you help me ?

**Comment by Herysia** [comment]
Hi, this project uses Reactor, i suggest you to first install the sample Reactor plugin using their documentation and try again after:
https://docs.reactor.gg/docs
You can also join their discord if you need help regarding reactor.

If you don't know reactor yet, it is a modding framework for among us which allow you to develop mods using unobfuscated names, as well as some useful tools.

**Comment by kfill420** [comment]
Ah yes sorry I forgot to add Reactor-Essentials.
Sorry and thank you
