### ISSUE TITLE
Are there any plans to make this mod compatible with the newest version of Among Us?

### ISSUE THREAD

**Issue by FerbFloo** [Herysia/AmongUsTryhard#4]
I'd really love to use some of the features in this mod again, as they really help to balance the game (especially if you're playing with an extra roles mod) Pleaaaase update^^

**Comment by Herysia** [comment]
Hey, I don't have much time lately, i'll update it once the map is released as there will be more changes to do

**Comment by FerbFloo** [comment]
That makes me so happy to hear!
